GO_EASY_ON_ME = 1

include theos/makefiles/common.mk

BUNDLE_NAME = OSOpenApplication OSSystemCommands OSBrightness
OSOpenApplication_FILES = OSOpenApplication.mm
OSOpenApplication_INSTALL_PATH = /var/mobile/Library/OpenSiri/Bundles
OSOpenApplication_RESOURCE_DIRS = OSOpenApplication

OSSystemCommands_FILES = OSSystemCommands.mm
OSSystemCommands_FRAMEWORKS = UIKit
OSSystemCommands_INSTALL_PATH = /var/mobile/Library/OpenSiri/Bundles
OSSystemCommands_RESOURCE_DIRS = OSSystemCommands

OSBrightness_FILES = OSBrightness.mm
OSBrightness_FRAMEWORKS = UIKit
OSBrightness_INSTALL_PATH = /var/mobile/Library/OpenSiri/Bundles
OSBrightness_RESOURCE_DIRS = OSBrightness

include $(THEOS_MAKE_PATH)/bundle.mk