GO_EASY_ON_ME = 1
include theos/makefiles/common.mk

TWEAK_NAME = OpenSiri
OpenSiri_FILES = Tweak.xm
OpenSiri_FRAMEWORKS = UIKit Foundation CoreGraphics
SUBPROJECTS = opensiridylibs

include $(THEOS_MAKE_PATH)/tweak.mk
include $(THEOS_MAKE_PATH)/aggregate.mk