GO_EASY_ON_ME = 1

include theos/makefiles/common.mk

LIBRARY_NAME = openmusic openappstore openbrowser opencalculator opencamera opencalendar openclock opencompass opencontacts openfacebook opengamecenter openmaps openmessages opennotes openphone openphotos openreminders openstocks opentwitter openvideos openvoicememos openweather openyoutube opensettings openitunes openmail
openmusic_FILES = openmusic.mm
openmusic_FRAMEWORKS = UIKit Foundation
openmusic_INSTALL_PATH = /var/mobile/Library/OpenSiri/

openappstore_FILES = openappstore.mm
openappstore_FRAMEWORKS = UIKit Foundation
openappstore_INSTALL_PATH = /var/mobile/Library/OpenSiri/

openbrowser_FILES = openbrowser.mm
openbrowser_FRAMEWORKS = UIKit Foundation
openbrowser_INSTALL_PATH = /var/mobile/Library/OpenSiri/

opencalculator_FILES = opencalculator.mm
opencalculator_FRAMEWORKS = UIKit Foundation
opencalculator_INSTALL_PATH = /var/mobile/Library/OpenSiri/

opencalendar_FILES = opencalendar.mm
opencalendar_FRAMEWORKS = UIKit Foundation
opencalendar_INSTALL_PATH = /var/mobile/Library/OpenSiri/

opencamera_FILES = opencamera.mm
opencamera_FRAMEWORKS = UIKit Foundation
opencamera_INSTALL_PATH = /var/mobile/Library/OpenSiri/

openclock_FILES = openclock.mm
openclock_FRAMEWORKS = UIKit Foundation
openclock_INSTALL_PATH = /var/mobile/Library/OpenSiri/

opencompass_FILES = opencompass.mm
opencompass_FRAMEWORKS = UIKit Foundation
opencompass_INSTALL_PATH = /var/mobile/Library/OpenSiri/

opencontacts_FILES = opencontacts.mm
opencontacts_FRAMEWORKS = UIKit Foundation
opencontacts_INSTALL_PATH = /var/mobile/Library/OpenSiri/

openfacebook_FILES = openfacebook.mm
openfacebook_FRAMEWORKS = UIKit Foundation
openfacebook_INSTALL_PATH = /var/mobile/Library/OpenSiri/

opengamecenter_FILES = opengamecenter.mm
opengamecenter_FRAMEWORKS = UIKit Foundation
opengamecenter_INSTALL_PATH = /var/mobile/Library/OpenSiri/

openmail_FILES = openmail.mm
openmail_FRAMEWORKS = UIKit Foundation
openmail_INSTALL_PATH = /var/mobile/Library/OpenSiri/

openmaps_FILES = openmaps.mm
openmaps_FRAMEWORKS = UIKit Foundation
openmaps_INSTALL_PATH = /var/mobile/Library/OpenSiri/

openmessages_FILES = openmessages.mm
openmessages_FRAMEWORKS = UIKit Foundation
openmessages_INSTALL_PATH = /var/mobile/Library/OpenSiri/

opennotes_FILES = opennotes.mm
opennotes_FRAMEWORKS = UIKit Foundation
opennotes_INSTALL_PATH = /var/mobile/Library/OpenSiri/

openphone_FILES = openphone.mm
openphone_FRAMEWORKS = UIKit Foundation
openphone_INSTALL_PATH = /var/mobile/Library/OpenSiri/

openphotos_FILES = openphotos.mm
openphotos_FRAMEWORKS = UIKit Foundation
openphotos_INSTALL_PATH = /var/mobile/Library/OpenSiri/

openreminders_FILES = openreminders.mm
openreminders_FRAMEWORKS = UIKit Foundation
openreminders_INSTALL_PATH = /var/mobile/Library/OpenSiri/

openstocks_FILES = openstocks.mm
openstocks_FRAMEWORKS = UIKit Foundation
openstocks_INSTALL_PATH = /var/mobile/Library/OpenSiri/

opentwitter_FILES = opentwitter.mm
opentwitter_FRAMEWORKS = UIKit Foundation
opentwitter_INSTALL_PATH = /var/mobile/Library/OpenSiri/

openvideos_FILES = openvideos.mm
openvideos_FRAMEWORKS = UIKit Foundation
openvideos_INSTALL_PATH = /var/mobile/Library/OpenSiri/

openvoicememos_FILES = openvoicememos.mm
openvoicememos_FRAMEWORKS = UIKit Foundation
openvoicememos_INSTALL_PATH = /var/mobile/Library/OpenSiri/

openweather_FILES = openweather.mm
openweather_FRAMEWORKS = UIKit Foundation
openweather_INSTALL_PATH = /var/mobile/Library/OpenSiri/

openyoutube_FILES = openyoutube.mm
openyoutube_FRAMEWORKS = UIKit Foundation
openyoutube_INSTALL_PATH = /var/mobile/Library/OpenSiri/

openitunes_FILES = openitunes.mm
openitunes_FRAMEWORKS = UIKit Foundation
openitunes_INSTALL_PATH = /var/mobile/Library/OpenSiri/

opensettings_FILES = opensettings.mm
opensettings_FRAMEWORKS = UIKit Foundation
opensettings_INSTALL_PATH = /var/mobile/Library/OpenSiri/


include $(THEOS_MAKE_PATH)/library.mk
